#! /usr/bin/env bash

# Copyright (c) 2015 The Akaros Authors
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version. See LICENSE for details.
#
# Kevin Klues <klueska@gmail.com>

: ${DOCKER_IMAGEBASE:=klueska/akaros-devel}
: ${DOCKER_FILEBASE:=Dockerfile}

if [ "$#" -ne 1 ]; then
	echo "Usage: ${0} <tag>"
	echo "    Build a docker image for ${DOCKER_IMAGEBASE}:<tag>"
	echo "    from ${DOCKER_FILEBASE}-<tag>."
	exit 1
fi

tag=$1
image=${DOCKER_IMAGEBASE}:${tag}
currdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
dockerfile=${DOCKER_FILEBASE}-${tag}

if [ ! -f ${dockerfile} ]; then
	echo "Invalid Tag: ${dockerfile} does not exist!"
	exit 1
fi

docker build -t ${image} -f ${currdir}/${dockerfile} ${currdir}
