#! /usr/bin/env bash

# Copyright (c) 2015 The Akaros Authors
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version. See LICENSE for details.
#
# Kevin Klues <klueska@gmail.com>

: ${DOCKER_IMAGEBASE:=klueska/akaros-devel}

BUILD_TAGS="base \
            pkg-install \
            env-setup \
            host-user"

./cleanup
for t in ${BUILD_TAGS}; do
	./build ${t}
done
lastimg=${DOCKER_IMAGEBASE}:${t}
stableimg=${DOCKER_IMAGEBASE}:stable
docker tag -f ${lastimg} ${stableimg}
./cleanup
