#! /usr/bin/env bash

# Copyright (c) 2015 The Akaros Authors
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version. See LICENSE for details.
#
# Kevin Klues <klueska@gmail.com>

: ${DOCKER_IMAGEBASE:=klueska/akaros-devel}

# Remove all containers and defunct images associated with
# ${DOCKER_IMAGEBASE}
containers=$(docker ps | grep ${DOCKER_IMAGEBASE} | cut -f1 -d " ")
images=$(docker images | grep "<none>" | tr -s ' ' | cut -f3 -d " ")
if [ "${containers}" != "" ]; then
	docker rm -f ${containers}
fi
if [ "${images}" != "" ]; then
	docker rmi -f ${images}
fi
