# Copyright (c) 2015 The Akaros Authors
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version. See LICENSE for details.
#
# Kevin Klues <klueska@gmail.com>

FROM ubuntu:14.04
MAINTAINER Kevin Klues <klueska@gmail.com>

# Launch bash by default at boot
CMD ["/bin/bash"]

