# Copyright (c) 2015 The Akaros Authors
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version. See LICENSE for details.
#
# Kevin Klues <klueska@gmail.com>

FROM klueska/akaros-devel:base
MAINTAINER Kevin Klues <klueska@gmail.com>

# Install packages
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive \
		apt-get install -y \
			bison \
			build-essential \
			emacs \
			flex \
			gawk \
			git \
			man \
			ncurses-dev \
			openssh-server \
			qemu-kvm \
			qemu-system-x86 \
			screen \
			vim

# Expose port 22 for sshd
EXPOSE 22
