#! /usr/bin/env bash

# Copyright (c) 2015 The Akaros Authors
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version. See LICENSE for details.
#
# Kevin Klues <klueska@gmail.com>

: ${DOCKERIMAGE_BASE:=klueska/akaros-devel}

if [ "$#" -ne 1 ]; then
	echo "Usage: ${0} <tag>"
	echo "    Push a docker image to docker.io for"
	echo "    ${DOCKERIMAGE_BASE}:<tag>"
	exit 1
fi

tag=$1
image=${DOCKERIMAGE_BASE}:${tag}

docker push ${image}
